// *******************************************************************************
// Copyright (c) 2025 Elektrobit Automotive GmbH
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License Version 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// *******************************************************************************

////
Every asciidoc file in this document starts with the section level 0, i.e. a section like
....
= Title
....

When the file is included from another file within the document, the levels must be adjusted with the `leveloffset` attribute to the `include` directive at the point of inclusion, e.g.
....
include::file.adoc[leveloffset=+1]
....
////

= Context View

{hpcmw} functional clusters use the functionality provided by the SOCom library.

The SOCom library provides the <<provided_interfaces_socom>> public interfaces and is dependent on the <<provided_interfaces_common, interfaces of the Common>>, as well as the <<interface-view-core, interfaces provided by the core element>> and <<interface-view-mw_logging, interfaces provided by the mw_logging module>> components.

.Context diagram of SOCom
[plantuml, svg, align="center"]
....
include::models/context_diagram_socom.puml[]
....
