' *******************************************************************************
' Copyright (c) 2025 Elektrobit Automotive GmbH
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml
component "Functional cluster" as functional_cluster

package mw_socom {
    component "socom" as socom
    component "socom-common" as common
    socom -r-> common: depends
}

component core
component "base-logging" as logging

functional_cluster -d-> socom: uses
socom -d-> core: depends
socom -d-> logging: depends
@enduml
